// ignore_for_file: constant_identifier_names

enum NetworkExceptionType {
  BACKEND,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT,
  INTERNAL,
  SERVICE_UNAVAILABLE,
  TIME_OUT,
  NO_INTERNET,
  UNKNOWN,
  SUCCESS,
  NO_CONTENT,
  BAD_REQUEST,
  CONNECTION_TIMEOUT,
  CANCEL,
  RECEIVE_TIMEOUT,
  SEND_TIMEOUT,
  NO_INTERNET_CONNECTION,
  BAD_CERTIFICATE,
  UNPROCESSABLE_ENTITY, // Added 422 Unprocessable Entity
}